language: node_js
node_js: 11

before_install:
  - npm install coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  provider: script
  script: bash scripts/publish.sh
  on:
    tags: true
